// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_containerengine is a generated GoMock package.
package mock_containerengine

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	containerengine "github.com/oracle/oci-go-sdk/v65/containerengine"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateCluster mocks base method.
func (m *MockClient) CreateCluster(ctx context.Context, request containerengine.CreateClusterRequest) (containerengine.CreateClusterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, request)
	ret0, _ := ret[0].(containerengine.CreateClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockClientMockRecorder) CreateCluster(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockClient)(nil).CreateCluster), ctx, request)
}

// CreateKubeconfig mocks base method.
func (m *MockClient) CreateKubeconfig(ctx context.Context, request containerengine.CreateKubeconfigRequest) (containerengine.CreateKubeconfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKubeconfig", ctx, request)
	ret0, _ := ret[0].(containerengine.CreateKubeconfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKubeconfig indicates an expected call of CreateKubeconfig.
func (mr *MockClientMockRecorder) CreateKubeconfig(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKubeconfig", reflect.TypeOf((*MockClient)(nil).CreateKubeconfig), ctx, request)
}

// CreateNodePool mocks base method.
func (m *MockClient) CreateNodePool(ctx context.Context, request containerengine.CreateNodePoolRequest) (containerengine.CreateNodePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodePool", ctx, request)
	ret0, _ := ret[0].(containerengine.CreateNodePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodePool indicates an expected call of CreateNodePool.
func (mr *MockClientMockRecorder) CreateNodePool(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodePool", reflect.TypeOf((*MockClient)(nil).CreateNodePool), ctx, request)
}

// DeleteCluster mocks base method.
func (m *MockClient) DeleteCluster(ctx context.Context, request containerengine.DeleteClusterRequest) (containerengine.DeleteClusterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, request)
	ret0, _ := ret[0].(containerengine.DeleteClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockClientMockRecorder) DeleteCluster(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockClient)(nil).DeleteCluster), ctx, request)
}

// DeleteNodePool mocks base method.
func (m *MockClient) DeleteNodePool(ctx context.Context, request containerengine.DeleteNodePoolRequest) (containerengine.DeleteNodePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodePool", ctx, request)
	ret0, _ := ret[0].(containerengine.DeleteNodePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNodePool indicates an expected call of DeleteNodePool.
func (mr *MockClientMockRecorder) DeleteNodePool(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodePool", reflect.TypeOf((*MockClient)(nil).DeleteNodePool), ctx, request)
}

// GetCluster mocks base method.
func (m *MockClient) GetCluster(ctx context.Context, request containerengine.GetClusterRequest) (containerengine.GetClusterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, request)
	ret0, _ := ret[0].(containerengine.GetClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockClientMockRecorder) GetCluster(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockClient)(nil).GetCluster), ctx, request)
}

// GetNodePool mocks base method.
func (m *MockClient) GetNodePool(ctx context.Context, request containerengine.GetNodePoolRequest) (containerengine.GetNodePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodePool", ctx, request)
	ret0, _ := ret[0].(containerengine.GetNodePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodePool indicates an expected call of GetNodePool.
func (mr *MockClientMockRecorder) GetNodePool(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodePool", reflect.TypeOf((*MockClient)(nil).GetNodePool), ctx, request)
}

// GetNodePoolOptions mocks base method.
func (m *MockClient) GetNodePoolOptions(ctx context.Context, request containerengine.GetNodePoolOptionsRequest) (containerengine.GetNodePoolOptionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodePoolOptions", ctx, request)
	ret0, _ := ret[0].(containerengine.GetNodePoolOptionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodePoolOptions indicates an expected call of GetNodePoolOptions.
func (mr *MockClientMockRecorder) GetNodePoolOptions(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodePoolOptions", reflect.TypeOf((*MockClient)(nil).GetNodePoolOptions), ctx, request)
}

// GetWorkRequest mocks base method.
func (m *MockClient) GetWorkRequest(ctx context.Context, request containerengine.GetWorkRequestRequest) (containerengine.GetWorkRequestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkRequest", ctx, request)
	ret0, _ := ret[0].(containerengine.GetWorkRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkRequest indicates an expected call of GetWorkRequest.
func (mr *MockClientMockRecorder) GetWorkRequest(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkRequest", reflect.TypeOf((*MockClient)(nil).GetWorkRequest), ctx, request)
}

// ListClusters mocks base method.
func (m *MockClient) ListClusters(ctx context.Context, request containerengine.ListClustersRequest) (containerengine.ListClustersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", ctx, request)
	ret0, _ := ret[0].(containerengine.ListClustersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockClientMockRecorder) ListClusters(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockClient)(nil).ListClusters), ctx, request)
}

// ListNodePools mocks base method.
func (m *MockClient) ListNodePools(ctx context.Context, request containerengine.ListNodePoolsRequest) (containerengine.ListNodePoolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodePools", ctx, request)
	ret0, _ := ret[0].(containerengine.ListNodePoolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodePools indicates an expected call of ListNodePools.
func (mr *MockClientMockRecorder) ListNodePools(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodePools", reflect.TypeOf((*MockClient)(nil).ListNodePools), ctx, request)
}

// UpdateCluster mocks base method.
func (m *MockClient) UpdateCluster(ctx context.Context, request containerengine.UpdateClusterRequest) (containerengine.UpdateClusterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCluster", ctx, request)
	ret0, _ := ret[0].(containerengine.UpdateClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockClientMockRecorder) UpdateCluster(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockClient)(nil).UpdateCluster), ctx, request)
}

// UpdateNodePool mocks base method.
func (m *MockClient) UpdateNodePool(ctx context.Context, request containerengine.UpdateNodePoolRequest) (containerengine.UpdateNodePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodePool", ctx, request)
	ret0, _ := ret[0].(containerengine.UpdateNodePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNodePool indicates an expected call of UpdateNodePool.
func (mr *MockClientMockRecorder) UpdateNodePool(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodePool", reflect.TypeOf((*MockClient)(nil).UpdateNodePool), ctx, request)
}
