// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_volume is a generated GoMock package.
package mock_volume

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/oracle/oci-go-sdk/v65/core"
)

// MockBlockVolumeClient is a mock of BlockVolumeClient interface.
type MockBlockVolumeClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlockVolumeClientMockRecorder
}

// MockBlockVolumeClientMockRecorder is the mock recorder for MockBlockVolumeClient.
type MockBlockVolumeClientMockRecorder struct {
	mock *MockBlockVolumeClient
}

// NewMockBlockVolumeClient creates a new mock instance.
func NewMockBlockVolumeClient(ctrl *gomock.Controller) *MockBlockVolumeClient {
	mock := &MockBlockVolumeClient{ctrl: ctrl}
	mock.recorder = &MockBlockVolumeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockVolumeClient) EXPECT() *MockBlockVolumeClientMockRecorder {
	return m.recorder
}

// DeleteVolume mocks base method.
func (m *MockBlockVolumeClient) DeleteVolume(ctx context.Context, request core.DeleteVolumeRequest) (core.DeleteVolumeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", ctx, request)
	ret0, _ := ret[0].(core.DeleteVolumeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockBlockVolumeClientMockRecorder) DeleteVolume(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockBlockVolumeClient)(nil).DeleteVolume), ctx, request)
}

// GetVolume mocks base method.
func (m *MockBlockVolumeClient) GetVolume(ctx context.Context, request core.GetVolumeRequest) (core.GetVolumeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", ctx, request)
	ret0, _ := ret[0].(core.GetVolumeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockBlockVolumeClientMockRecorder) GetVolume(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockBlockVolumeClient)(nil).GetVolume), ctx, request)
}

// CreateVolume mocks base method.
func (m *MockBlockVolumeClient) CreateVolume(ctx context.Context, request core.CreateVolumeRequest) (core.CreateVolumeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", ctx, request)
	ret0, _ := ret[0].(core.CreateVolumeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of LaunchVolume.
func (mr *MockBlockVolumeClientMockRecorder) CreateVolume(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockBlockVolumeClient)(nil).CreateVolume), ctx, request)
}

// ListVolumes mocks base method.
func (m *MockBlockVolumeClient) ListVolumes(ctx context.Context, request core.ListVolumesRequest) (core.ListVolumesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", ctx, request)
	ret0, _ := ret[0].(core.ListVolumesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockBlockVolumeClientMockRecorder) ListVolumes(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockBlockVolumeClient)(nil).ListVolumes), ctx, request)
}
