//go:build !ignore_autogenerated

/*
Copyright (c) 2022, Oracle and/or its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddOnOptions) DeepCopyInto(out *AddOnOptions) {
	*out = *in
	if in.IsKubernetesDashboardEnabled != nil {
		in, out := &in.IsKubernetesDashboardEnabled, &out.IsKubernetesDashboardEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTillerEnabled != nil {
		in, out := &in.IsTillerEnabled, &out.IsTillerEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddOnOptions.
func (in *AddOnOptions) DeepCopy() *AddOnOptions {
	if in == nil {
		return nil
	}
	out := new(AddOnOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionControllerOptions) DeepCopyInto(out *AdmissionControllerOptions) {
	*out = *in
	if in.IsPodSecurityPolicyEnabled != nil {
		in, out := &in.IsPodSecurityPolicyEnabled, &out.IsPodSecurityPolicyEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionControllerOptions.
func (in *AdmissionControllerOptions) DeepCopy() *AdmissionControllerOptions {
	if in == nil {
		return nil
	}
	out := new(AdmissionControllerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedNamespaces) DeepCopyInto(out *AllowedNamespaces) {
	*out = *in
	if in.NamespaceList != nil {
		in, out := &in.NamespaceList, &out.NamespaceList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedNamespaces.
func (in *AllowedNamespaces) DeepCopy() *AllowedNamespaces {
	if in == nil {
		return nil
	}
	out := new(AllowedNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmdMilanBmPlatformConfig) DeepCopyInto(out *AmdMilanBmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSymmetricMultiThreadingEnabled != nil {
		in, out := &in.IsSymmetricMultiThreadingEnabled, &out.IsSymmetricMultiThreadingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsAccessControlServiceEnabled != nil {
		in, out := &in.IsAccessControlServiceEnabled, &out.IsAccessControlServiceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AreVirtualInstructionsEnabled != nil {
		in, out := &in.AreVirtualInstructionsEnabled, &out.AreVirtualInstructionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsInputOutputMemoryManagementUnitEnabled != nil {
		in, out := &in.IsInputOutputMemoryManagementUnitEnabled, &out.IsInputOutputMemoryManagementUnitEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PercentageOfCoresEnabled != nil {
		in, out := &in.PercentageOfCoresEnabled, &out.PercentageOfCoresEnabled
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmdMilanBmPlatformConfig.
func (in *AmdMilanBmPlatformConfig) DeepCopy() *AmdMilanBmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(AmdMilanBmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmdRomeBmGpuPlatformConfig) DeepCopyInto(out *AmdRomeBmGpuPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSymmetricMultiThreadingEnabled != nil {
		in, out := &in.IsSymmetricMultiThreadingEnabled, &out.IsSymmetricMultiThreadingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsAccessControlServiceEnabled != nil {
		in, out := &in.IsAccessControlServiceEnabled, &out.IsAccessControlServiceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AreVirtualInstructionsEnabled != nil {
		in, out := &in.AreVirtualInstructionsEnabled, &out.AreVirtualInstructionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsInputOutputMemoryManagementUnitEnabled != nil {
		in, out := &in.IsInputOutputMemoryManagementUnitEnabled, &out.IsInputOutputMemoryManagementUnitEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmdRomeBmGpuPlatformConfig.
func (in *AmdRomeBmGpuPlatformConfig) DeepCopy() *AmdRomeBmGpuPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(AmdRomeBmGpuPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmdRomeBmPlatformConfig) DeepCopyInto(out *AmdRomeBmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSymmetricMultiThreadingEnabled != nil {
		in, out := &in.IsSymmetricMultiThreadingEnabled, &out.IsSymmetricMultiThreadingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsAccessControlServiceEnabled != nil {
		in, out := &in.IsAccessControlServiceEnabled, &out.IsAccessControlServiceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AreVirtualInstructionsEnabled != nil {
		in, out := &in.AreVirtualInstructionsEnabled, &out.AreVirtualInstructionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsInputOutputMemoryManagementUnitEnabled != nil {
		in, out := &in.IsInputOutputMemoryManagementUnitEnabled, &out.IsInputOutputMemoryManagementUnitEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PercentageOfCoresEnabled != nil {
		in, out := &in.PercentageOfCoresEnabled, &out.PercentageOfCoresEnabled
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmdRomeBmPlatformConfig.
func (in *AmdRomeBmPlatformConfig) DeepCopy() *AmdRomeBmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(AmdRomeBmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmdVmPlatformConfig) DeepCopyInto(out *AmdVmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmdVmPlatformConfig.
func (in *AmdVmPlatformConfig) DeepCopy() *AmdVmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(AmdVmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSetDetails) DeepCopyInto(out *BackendSetDetails) {
	*out = *in
	if in.IsPreserveSource != nil {
		in, out := &in.IsPreserveSource, &out.IsPreserveSource
		*out = new(bool)
		**out = **in
	}
	if in.IsFailOpen != nil {
		in, out := &in.IsFailOpen, &out.IsFailOpen
		*out = new(bool)
		**out = **in
	}
	if in.IsInstantFailoverEnabled != nil {
		in, out := &in.IsInstantFailoverEnabled, &out.IsInstantFailoverEnabled
		*out = new(bool)
		**out = **in
	}
	in.HealthChecker.DeepCopyInto(&out.HealthChecker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSetDetails.
func (in *BackendSetDetails) DeepCopy() *BackendSetDetails {
	if in == nil {
		return nil
	}
	out := new(BackendSetDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOptions) DeepCopyInto(out *ClusterOptions) {
	*out = *in
	if in.AddOnOptions != nil {
		in, out := &in.AddOnOptions, &out.AddOnOptions
		*out = new(AddOnOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AdmissionControllerOptions != nil {
		in, out := &in.AdmissionControllerOptions, &out.AdmissionControllerOptions
		*out = new(AdmissionControllerOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOptions.
func (in *ClusterOptions) DeepCopy() *ClusterOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPodNetworkOptions) DeepCopyInto(out *ClusterPodNetworkOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPodNetworkOptions.
func (in *ClusterPodNetworkOptions) DeepCopy() *ClusterPodNetworkOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterPodNetworkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRG) DeepCopyInto(out *DRG) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.VcnAttachmentId != nil {
		in, out := &in.VcnAttachmentId, &out.VcnAttachmentId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRG.
func (in *DRG) DeepCopy() *DRG {
	if in == nil {
		return nil
	}
	out := new(DRG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressSecurityRule) DeepCopyInto(out *EgressSecurityRule) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.IcmpOptions != nil {
		in, out := &in.IcmpOptions, &out.IcmpOptions
		*out = new(IcmpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IsStateless != nil {
		in, out := &in.IsStateless, &out.IsStateless
		*out = new(bool)
		**out = **in
	}
	if in.TcpOptions != nil {
		in, out := &in.TcpOptions, &out.TcpOptions
		*out = new(TcpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.UdpOptions != nil {
		in, out := &in.UdpOptions, &out.UdpOptions
		*out = new(UdpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressSecurityRule.
func (in *EgressSecurityRule) DeepCopy() *EgressSecurityRule {
	if in == nil {
		return nil
	}
	out := new(EgressSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressSecurityRuleForNSG) DeepCopyInto(out *EgressSecurityRuleForNSG) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	in.EgressSecurityRule.DeepCopyInto(&out.EgressSecurityRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressSecurityRuleForNSG.
func (in *EgressSecurityRuleForNSG) DeepCopy() *EgressSecurityRuleForNSG {
	if in == nil {
		return nil
	}
	out := new(EgressSecurityRuleForNSG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfig) DeepCopyInto(out *EndpointConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfig.
func (in *EndpointConfig) DeepCopy() *EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthChecker) DeepCopyInto(out *HealthChecker) {
	*out = *in
	if in.UrlPath != nil {
		in, out := &in.UrlPath, &out.UrlPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthChecker.
func (in *HealthChecker) DeepCopy() *HealthChecker {
	if in == nil {
		return nil
	}
	out := new(HealthChecker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcmpOptions) DeepCopyInto(out *IcmpOptions) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(int)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcmpOptions.
func (in *IcmpOptions) DeepCopy() *IcmpOptions {
	if in == nil {
		return nil
	}
	out := new(IcmpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePolicyConfig) DeepCopyInto(out *ImagePolicyConfig) {
	*out = *in
	if in.IsPolicyEnabled != nil {
		in, out := &in.IsPolicyEnabled, &out.IsPolicyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.KeyDetails != nil {
		in, out := &in.KeyDetails, &out.KeyDetails
		*out = make([]KeyDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePolicyConfig.
func (in *ImagePolicyConfig) DeepCopy() *ImagePolicyConfig {
	if in == nil {
		return nil
	}
	out := new(ImagePolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSecurityRule) DeepCopyInto(out *IngressSecurityRule) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.IcmpOptions != nil {
		in, out := &in.IcmpOptions, &out.IcmpOptions
		*out = new(IcmpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IsStateless != nil {
		in, out := &in.IsStateless, &out.IsStateless
		*out = new(bool)
		**out = **in
	}
	if in.TcpOptions != nil {
		in, out := &in.TcpOptions, &out.TcpOptions
		*out = new(TcpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.UdpOptions != nil {
		in, out := &in.UdpOptions, &out.UdpOptions
		*out = new(UdpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSecurityRule.
func (in *IngressSecurityRule) DeepCopy() *IngressSecurityRule {
	if in == nil {
		return nil
	}
	out := new(IngressSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSecurityRuleForNSG) DeepCopyInto(out *IngressSecurityRuleForNSG) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	in.IngressSecurityRule.DeepCopyInto(&out.IngressSecurityRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSecurityRuleForNSG.
func (in *IngressSecurityRuleForNSG) DeepCopy() *IngressSecurityRuleForNSG {
	if in == nil {
		return nil
	}
	out := new(IngressSecurityRuleForNSG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceAgentPluginConfig) DeepCopyInto(out *InstanceAgentPluginConfig) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceAgentPluginConfig.
func (in *InstanceAgentPluginConfig) DeepCopy() *InstanceAgentPluginConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceAgentPluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceOptions) DeepCopyInto(out *InstanceOptions) {
	*out = *in
	if in.AreLegacyImdsEndpointsDisabled != nil {
		in, out := &in.AreLegacyImdsEndpointsDisabled, &out.AreLegacyImdsEndpointsDisabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceOptions.
func (in *InstanceOptions) DeepCopy() *InstanceOptions {
	if in == nil {
		return nil
	}
	out := new(InstanceOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSourceViaImageConfig) DeepCopyInto(out *InstanceSourceViaImageConfig) {
	*out = *in
	if in.KmsKeyId != nil {
		in, out := &in.KmsKeyId, &out.KmsKeyId
		*out = new(string)
		**out = **in
	}
	if in.BootVolumeVpusPerGB != nil {
		in, out := &in.BootVolumeVpusPerGB, &out.BootVolumeVpusPerGB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSourceViaImageConfig.
func (in *InstanceSourceViaImageConfig) DeepCopy() *InstanceSourceViaImageConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceSourceViaImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelIcelakeBmPlatformConfig) DeepCopyInto(out *IntelIcelakeBmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSymmetricMultiThreadingEnabled != nil {
		in, out := &in.IsSymmetricMultiThreadingEnabled, &out.IsSymmetricMultiThreadingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsInputOutputMemoryManagementUnitEnabled != nil {
		in, out := &in.IsInputOutputMemoryManagementUnitEnabled, &out.IsInputOutputMemoryManagementUnitEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PercentageOfCoresEnabled != nil {
		in, out := &in.PercentageOfCoresEnabled, &out.PercentageOfCoresEnabled
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelIcelakeBmPlatformConfig.
func (in *IntelIcelakeBmPlatformConfig) DeepCopy() *IntelIcelakeBmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(IntelIcelakeBmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelSkylakeBmPlatformConfig) DeepCopyInto(out *IntelSkylakeBmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelSkylakeBmPlatformConfig.
func (in *IntelSkylakeBmPlatformConfig) DeepCopy() *IntelSkylakeBmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(IntelSkylakeBmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelVmPlatformConfig) DeepCopyInto(out *IntelVmPlatformConfig) {
	*out = *in
	if in.IsSecureBootEnabled != nil {
		in, out := &in.IsSecureBootEnabled, &out.IsSecureBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsTrustedPlatformModuleEnabled != nil {
		in, out := &in.IsTrustedPlatformModuleEnabled, &out.IsTrustedPlatformModuleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMeasuredBootEnabled != nil {
		in, out := &in.IsMeasuredBootEnabled, &out.IsMeasuredBootEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsMemoryEncryptionEnabled != nil {
		in, out := &in.IsMemoryEncryptionEnabled, &out.IsMemoryEncryptionEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelVmPlatformConfig.
func (in *IntelVmPlatformConfig) DeepCopy() *IntelVmPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(IntelVmPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyDetails) DeepCopyInto(out *KeyDetails) {
	*out = *in
	if in.KmsKeyId != nil {
		in, out := &in.KmsKeyId, &out.KmsKeyId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyDetails.
func (in *KeyDetails) DeepCopy() *KeyDetails {
	if in == nil {
		return nil
	}
	out := new(KeyDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesNetworkConfig) DeepCopyInto(out *KubernetesNetworkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesNetworkConfig.
func (in *KubernetesNetworkConfig) DeepCopy() *KubernetesNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchCreateVolumeFromAttributes) DeepCopyInto(out *LaunchCreateVolumeFromAttributes) {
	*out = *in
	if in.SizeInGBs != nil {
		in, out := &in.SizeInGBs, &out.SizeInGBs
		*out = new(int64)
		**out = **in
	}
	if in.CompartmentId != nil {
		in, out := &in.CompartmentId, &out.CompartmentId
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.KmsKeyId != nil {
		in, out := &in.KmsKeyId, &out.KmsKeyId
		*out = new(string)
		**out = **in
	}
	if in.VpusPerGB != nil {
		in, out := &in.VpusPerGB, &out.VpusPerGB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchCreateVolumeFromAttributes.
func (in *LaunchCreateVolumeFromAttributes) DeepCopy() *LaunchCreateVolumeFromAttributes {
	if in == nil {
		return nil
	}
	out := new(LaunchCreateVolumeFromAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchInstanceAgentConfig) DeepCopyInto(out *LaunchInstanceAgentConfig) {
	*out = *in
	if in.IsMonitoringDisabled != nil {
		in, out := &in.IsMonitoringDisabled, &out.IsMonitoringDisabled
		*out = new(bool)
		**out = **in
	}
	if in.IsManagementDisabled != nil {
		in, out := &in.IsManagementDisabled, &out.IsManagementDisabled
		*out = new(bool)
		**out = **in
	}
	if in.AreAllPluginsDisabled != nil {
		in, out := &in.AreAllPluginsDisabled, &out.AreAllPluginsDisabled
		*out = new(bool)
		**out = **in
	}
	if in.PluginsConfig != nil {
		in, out := &in.PluginsConfig, &out.PluginsConfig
		*out = make([]InstanceAgentPluginConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchInstanceAgentConfig.
func (in *LaunchInstanceAgentConfig) DeepCopy() *LaunchInstanceAgentConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchInstanceAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchInstanceAvailabilityConfig) DeepCopyInto(out *LaunchInstanceAvailabilityConfig) {
	*out = *in
	if in.IsLiveMigrationPreferred != nil {
		in, out := &in.IsLiveMigrationPreferred, &out.IsLiveMigrationPreferred
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchInstanceAvailabilityConfig.
func (in *LaunchInstanceAvailabilityConfig) DeepCopy() *LaunchInstanceAvailabilityConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchInstanceAvailabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchIscsiVolumeAttachment) DeepCopyInto(out *LaunchIscsiVolumeAttachment) {
	*out = *in
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IsReadOnly != nil {
		in, out := &in.IsReadOnly, &out.IsReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.IsShareable != nil {
		in, out := &in.IsShareable, &out.IsShareable
		*out = new(bool)
		**out = **in
	}
	if in.VolumeId != nil {
		in, out := &in.VolumeId, &out.VolumeId
		*out = new(string)
		**out = **in
	}
	in.LaunchCreateVolumeFromAttributes.DeepCopyInto(&out.LaunchCreateVolumeFromAttributes)
	if in.UseChap != nil {
		in, out := &in.UseChap, &out.UseChap
		*out = new(bool)
		**out = **in
	}
	if in.IsAgentAutoIscsiLoginEnabled != nil {
		in, out := &in.IsAgentAutoIscsiLoginEnabled, &out.IsAgentAutoIscsiLoginEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchIscsiVolumeAttachment.
func (in *LaunchIscsiVolumeAttachment) DeepCopy() *LaunchIscsiVolumeAttachment {
	if in == nil {
		return nil
	}
	out := new(LaunchIscsiVolumeAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchOptions) DeepCopyInto(out *LaunchOptions) {
	*out = *in
	if in.IsConsistentVolumeNamingEnabled != nil {
		in, out := &in.IsConsistentVolumeNamingEnabled, &out.IsConsistentVolumeNamingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchOptions.
func (in *LaunchOptions) DeepCopy() *LaunchOptions {
	if in == nil {
		return nil
	}
	out := new(LaunchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchParavirtualizedVolumeAttachment) DeepCopyInto(out *LaunchParavirtualizedVolumeAttachment) {
	*out = *in
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IsReadOnly != nil {
		in, out := &in.IsReadOnly, &out.IsReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.IsShareable != nil {
		in, out := &in.IsShareable, &out.IsShareable
		*out = new(bool)
		**out = **in
	}
	if in.VolumeId != nil {
		in, out := &in.VolumeId, &out.VolumeId
		*out = new(string)
		**out = **in
	}
	in.LaunchCreateVolumeFromAttributes.DeepCopyInto(&out.LaunchCreateVolumeFromAttributes)
	if in.IsPvEncryptionInTransitEnabled != nil {
		in, out := &in.IsPvEncryptionInTransitEnabled, &out.IsPvEncryptionInTransitEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchParavirtualizedVolumeAttachment.
func (in *LaunchParavirtualizedVolumeAttachment) DeepCopy() *LaunchParavirtualizedVolumeAttachment {
	if in == nil {
		return nil
	}
	out := new(LaunchParavirtualizedVolumeAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchVolumeAttachment) DeepCopyInto(out *LaunchVolumeAttachment) {
	*out = *in
	in.IscsiAttachment.DeepCopyInto(&out.IscsiAttachment)
	in.ParavirtualizedAttachment.DeepCopyInto(&out.ParavirtualizedAttachment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchVolumeAttachment.
func (in *LaunchVolumeAttachment) DeepCopy() *LaunchVolumeAttachment {
	if in == nil {
		return nil
	}
	out := new(LaunchVolumeAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	if in.LoadBalancerId != nil {
		in, out := &in.LoadBalancerId, &out.LoadBalancerId
		*out = new(string)
		**out = **in
	}
	in.NLBSpec.DeepCopyInto(&out.NLBSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLBSpec) DeepCopyInto(out *NLBSpec) {
	*out = *in
	in.BackendSetDetails.DeepCopyInto(&out.BackendSetDetails)
	if in.ReservedIpIds != nil {
		in, out := &in.ReservedIpIds, &out.ReservedIpIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBSpec.
func (in *NLBSpec) DeepCopy() *NLBSpec {
	if in == nil {
		return nil
	}
	out := new(NLBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NSG) DeepCopyInto(out *NSG) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.EgressRules != nil {
		in, out := &in.EgressRules, &out.EgressRules
		*out = make([]EgressSecurityRuleForNSG, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IngressRules != nil {
		in, out := &in.IngressRules, &out.IngressRules
		*out = make([]IngressSecurityRuleForNSG, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NSG.
func (in *NSG) DeepCopy() *NSG {
	if in == nil {
		return nil
	}
	out := new(NSG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkDetails) DeepCopyInto(out *NetworkDetails) {
	*out = *in
	if in.SubnetId != nil {
		in, out := &in.SubnetId, &out.SubnetId
		*out = new(string)
		**out = **in
	}
	if in.NSGId != nil {
		in, out := &in.NSGId, &out.NSGId
		*out = new(string)
		**out = **in
	}
	if in.NSGIds != nil {
		in, out := &in.NSGIds, &out.NSGIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SkipSourceDestCheck != nil {
		in, out := &in.SkipSourceDestCheck, &out.SkipSourceDestCheck
		*out = new(bool)
		**out = **in
	}
	if in.NsgNames != nil {
		in, out := &in.NsgNames, &out.NsgNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostnameLabel != nil {
		in, out := &in.HostnameLabel, &out.HostnameLabel
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.AssignPrivateDnsRecord != nil {
		in, out := &in.AssignPrivateDnsRecord, &out.AssignPrivateDnsRecord
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkDetails.
func (in *NetworkDetails) DeepCopy() *NetworkDetails {
	if in == nil {
		return nil
	}
	out := new(NetworkDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	in.Vcn.DeepCopyInto(&out.Vcn)
	in.APIServerLB.DeepCopyInto(&out.APIServerLB)
	if in.VCNPeering != nil {
		in, out := &in.VCNPeering, &out.VCNPeering
		*out = new(VCNPeering)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIAvailabilityDomain) DeepCopyInto(out *OCIAvailabilityDomain) {
	*out = *in
	if in.FaultDomains != nil {
		in, out := &in.FaultDomains, &out.FaultDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIAvailabilityDomain.
func (in *OCIAvailabilityDomain) DeepCopy() *OCIAvailabilityDomain {
	if in == nil {
		return nil
	}
	out := new(OCIAvailabilityDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCICluster) DeepCopyInto(out *OCICluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCICluster.
func (in *OCICluster) DeepCopy() *OCICluster {
	if in == nil {
		return nil
	}
	out := new(OCICluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCICluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterIdentity) DeepCopyInto(out *OCIClusterIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterIdentity.
func (in *OCIClusterIdentity) DeepCopy() *OCIClusterIdentity {
	if in == nil {
		return nil
	}
	out := new(OCIClusterIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterIdentityList) DeepCopyInto(out *OCIClusterIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIClusterIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterIdentityList.
func (in *OCIClusterIdentityList) DeepCopy() *OCIClusterIdentityList {
	if in == nil {
		return nil
	}
	out := new(OCIClusterIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterIdentitySpec) DeepCopyInto(out *OCIClusterIdentitySpec) {
	*out = *in
	out.PrincipalSecret = in.PrincipalSecret
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = new(AllowedNamespaces)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterIdentitySpec.
func (in *OCIClusterIdentitySpec) DeepCopy() *OCIClusterIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(OCIClusterIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterIdentityStatus) DeepCopyInto(out *OCIClusterIdentityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterIdentityStatus.
func (in *OCIClusterIdentityStatus) DeepCopy() *OCIClusterIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(OCIClusterIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterList) DeepCopyInto(out *OCIClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCICluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterList.
func (in *OCIClusterList) DeepCopy() *OCIClusterList {
	if in == nil {
		return nil
	}
	out := new(OCIClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterSpec) DeepCopyInto(out *OCIClusterSpec) {
	*out = *in
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterSpec.
func (in *OCIClusterSpec) DeepCopy() *OCIClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OCIClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterStatus) DeepCopyInto(out *OCIClusterStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AvailabilityDomains != nil {
		in, out := &in.AvailabilityDomains, &out.AvailabilityDomains
		*out = make(map[string]OCIAvailabilityDomain, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterStatus.
func (in *OCIClusterStatus) DeepCopy() *OCIClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OCIClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterTemplate) DeepCopyInto(out *OCIClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterTemplate.
func (in *OCIClusterTemplate) DeepCopy() *OCIClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(OCIClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterTemplateList) DeepCopyInto(out *OCIClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterTemplateList.
func (in *OCIClusterTemplateList) DeepCopy() *OCIClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(OCIClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterTemplateResource) DeepCopyInto(out *OCIClusterTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterTemplateResource.
func (in *OCIClusterTemplateResource) DeepCopy() *OCIClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OCIClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterTemplateSpec) DeepCopyInto(out *OCIClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterTemplateSpec.
func (in *OCIClusterTemplateSpec) DeepCopy() *OCIClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OCIClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachine) DeepCopyInto(out *OCIMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachine.
func (in *OCIMachine) DeepCopy() *OCIMachine {
	if in == nil {
		return nil
	}
	out := new(OCIMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineList) DeepCopyInto(out *OCIMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineList.
func (in *OCIMachineList) DeepCopy() *OCIMachineList {
	if in == nil {
		return nil
	}
	out := new(OCIMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineSpec) DeepCopyInto(out *OCIMachineSpec) {
	*out = *in
	if in.InstanceId != nil {
		in, out := &in.InstanceId, &out.InstanceId
		*out = new(string)
		**out = **in
	}
	if in.ComputeClusterId != nil {
		in, out := &in.ComputeClusterId, &out.ComputeClusterId
		*out = new(string)
		**out = **in
	}
	if in.IpxeScript != nil {
		in, out := &in.IpxeScript, &out.IpxeScript
		*out = new(string)
		**out = **in
	}
	if in.CapacityReservationId != nil {
		in, out := &in.CapacityReservationId, &out.CapacityReservationId
		*out = new(string)
		**out = **in
	}
	in.ShapeConfig.DeepCopyInto(&out.ShapeConfig)
	in.NetworkDetails.DeepCopyInto(&out.NetworkDetails)
	if in.VnicAttachments != nil {
		in, out := &in.VnicAttachments, &out.VnicAttachments
		*out = make([]VnicAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LaunchOptions != nil {
		in, out := &in.LaunchOptions, &out.LaunchOptions
		*out = new(LaunchOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceOptions != nil {
		in, out := &in.InstanceOptions, &out.InstanceOptions
		*out = new(InstanceOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AvailabilityConfig != nil {
		in, out := &in.AvailabilityConfig, &out.AvailabilityConfig
		*out = new(LaunchInstanceAvailabilityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PreemptibleInstanceConfig != nil {
		in, out := &in.PreemptibleInstanceConfig, &out.PreemptibleInstanceConfig
		*out = new(PreemptibleInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentConfig != nil {
		in, out := &in.AgentConfig, &out.AgentConfig
		*out = new(LaunchInstanceAgentConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceSourceViaImageDetails != nil {
		in, out := &in.InstanceSourceViaImageDetails, &out.InstanceSourceViaImageDetails
		*out = new(InstanceSourceViaImageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PlatformConfig != nil {
		in, out := &in.PlatformConfig, &out.PlatformConfig
		*out = new(PlatformConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DedicatedVmHostId != nil {
		in, out := &in.DedicatedVmHostId, &out.DedicatedVmHostId
		*out = new(string)
		**out = **in
	}
	if in.LaunchVolumeAttachment != nil {
		in, out := &in.LaunchVolumeAttachment, &out.LaunchVolumeAttachment
		*out = make([]LaunchVolumeAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineSpec.
func (in *OCIMachineSpec) DeepCopy() *OCIMachineSpec {
	if in == nil {
		return nil
	}
	out := new(OCIMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineStatus) DeepCopyInto(out *OCIMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]corev1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineStatus.
func (in *OCIMachineStatus) DeepCopy() *OCIMachineStatus {
	if in == nil {
		return nil
	}
	out := new(OCIMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineTemplate) DeepCopyInto(out *OCIMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineTemplate.
func (in *OCIMachineTemplate) DeepCopy() *OCIMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(OCIMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineTemplateList) DeepCopyInto(out *OCIMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineTemplateList.
func (in *OCIMachineTemplateList) DeepCopy() *OCIMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(OCIMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineTemplateResource) DeepCopyInto(out *OCIMachineTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineTemplateResource.
func (in *OCIMachineTemplateResource) DeepCopy() *OCIMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OCIMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMachineTemplateSpec) DeepCopyInto(out *OCIMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMachineTemplateSpec.
func (in *OCIMachineTemplateSpec) DeepCopy() *OCIMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OCIMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedCluster) DeepCopyInto(out *OCIManagedCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedCluster.
func (in *OCIManagedCluster) DeepCopy() *OCIManagedCluster {
	if in == nil {
		return nil
	}
	out := new(OCIManagedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterList) DeepCopyInto(out *OCIManagedClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIManagedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterList.
func (in *OCIManagedClusterList) DeepCopy() *OCIManagedClusterList {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterSpec) DeepCopyInto(out *OCIManagedClusterSpec) {
	*out = *in
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	in.NetworkSpec.DeepCopyInto(&out.NetworkSpec)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterSpec.
func (in *OCIManagedClusterSpec) DeepCopy() *OCIManagedClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterStatus) DeepCopyInto(out *OCIManagedClusterStatus) {
	*out = *in
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(corev1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AvailabilityDomains != nil {
		in, out := &in.AvailabilityDomains, &out.AvailabilityDomains
		*out = make(map[string]OCIAvailabilityDomain, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterStatus.
func (in *OCIManagedClusterStatus) DeepCopy() *OCIManagedClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterTemplate) DeepCopyInto(out *OCIManagedClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterTemplate.
func (in *OCIManagedClusterTemplate) DeepCopy() *OCIManagedClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterTemplateList) DeepCopyInto(out *OCIManagedClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIManagedClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterTemplateList.
func (in *OCIManagedClusterTemplateList) DeepCopy() *OCIManagedClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterTemplateResource) DeepCopyInto(out *OCIManagedClusterTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterTemplateResource.
func (in *OCIManagedClusterTemplateResource) DeepCopy() *OCIManagedClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedClusterTemplateSpec) DeepCopyInto(out *OCIManagedClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedClusterTemplateSpec.
func (in *OCIManagedClusterTemplateSpec) DeepCopy() *OCIManagedClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OCIManagedClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlane) DeepCopyInto(out *OCIManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlane.
func (in *OCIManagedControlPlane) DeepCopy() *OCIManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneList) DeepCopyInto(out *OCIManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneList.
func (in *OCIManagedControlPlaneList) DeepCopy() *OCIManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneSpec) DeepCopyInto(out *OCIManagedControlPlaneSpec) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ClusterPodNetworkOptions != nil {
		in, out := &in.ClusterPodNetworkOptions, &out.ClusterPodNetworkOptions
		*out = make([]ClusterPodNetworkOptions, len(*in))
		copy(*out, *in)
	}
	if in.ImagePolicyConfig != nil {
		in, out := &in.ImagePolicyConfig, &out.ImagePolicyConfig
		*out = new(ImagePolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	in.ClusterOption.DeepCopyInto(&out.ClusterOption)
	if in.KmsKeyId != nil {
		in, out := &in.KmsKeyId, &out.KmsKeyId
		*out = new(string)
		**out = **in
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneSpec.
func (in *OCIManagedControlPlaneSpec) DeepCopy() *OCIManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneStatus) DeepCopyInto(out *OCIManagedControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(corev1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneStatus.
func (in *OCIManagedControlPlaneStatus) DeepCopy() *OCIManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneTemplate) DeepCopyInto(out *OCIManagedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneTemplate.
func (in *OCIManagedControlPlaneTemplate) DeepCopy() *OCIManagedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneTemplateList) DeepCopyInto(out *OCIManagedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIManagedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneTemplateList.
func (in *OCIManagedControlPlaneTemplateList) DeepCopy() *OCIManagedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIManagedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneTemplateResource) DeepCopyInto(out *OCIManagedControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneTemplateResource.
func (in *OCIManagedControlPlaneTemplateResource) DeepCopy() *OCIManagedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManagedControlPlaneTemplateSpec) DeepCopyInto(out *OCIManagedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManagedControlPlaneTemplateSpec.
func (in *OCIManagedControlPlaneTemplateSpec) DeepCopy() *OCIManagedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OCIManagedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerRouteRule) DeepCopyInto(out *PeerRouteRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerRouteRule.
func (in *PeerRouteRule) DeepCopy() *PeerRouteRule {
	if in == nil {
		return nil
	}
	out := new(PeerRouteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformConfig) DeepCopyInto(out *PlatformConfig) {
	*out = *in
	in.AmdMilanBmPlatformConfig.DeepCopyInto(&out.AmdMilanBmPlatformConfig)
	in.AmdRomeBmPlatformConfig.DeepCopyInto(&out.AmdRomeBmPlatformConfig)
	in.IntelSkylakeBmPlatformConfig.DeepCopyInto(&out.IntelSkylakeBmPlatformConfig)
	in.IntelIcelakeBmPlatformConfig.DeepCopyInto(&out.IntelIcelakeBmPlatformConfig)
	in.AmdRomeBmGpuPlatformConfig.DeepCopyInto(&out.AmdRomeBmGpuPlatformConfig)
	in.IntelVmPlatformConfig.DeepCopyInto(&out.IntelVmPlatformConfig)
	in.AmdVmPlatformConfig.DeepCopyInto(&out.AmdVmPlatformConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformConfig.
func (in *PlatformConfig) DeepCopy() *PlatformConfig {
	if in == nil {
		return nil
	}
	out := new(PlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRange.
func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreemptibleInstanceConfig) DeepCopyInto(out *PreemptibleInstanceConfig) {
	*out = *in
	if in.TerminatePreemptionAction != nil {
		in, out := &in.TerminatePreemptionAction, &out.TerminatePreemptionAction
		*out = new(TerminatePreemptionAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreemptibleInstanceConfig.
func (in *PreemptibleInstanceConfig) DeepCopy() *PreemptibleInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(PreemptibleInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotePeeringConnection) DeepCopyInto(out *RemotePeeringConnection) {
	*out = *in
	if in.PeerDRGId != nil {
		in, out := &in.PeerDRGId, &out.PeerDRGId
		*out = new(string)
		**out = **in
	}
	if in.PeerRPCConnectionId != nil {
		in, out := &in.PeerRPCConnectionId, &out.PeerRPCConnectionId
		*out = new(string)
		**out = **in
	}
	if in.RPCConnectionId != nil {
		in, out := &in.RPCConnectionId, &out.RPCConnectionId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotePeeringConnection.
func (in *RemotePeeringConnection) DeepCopy() *RemotePeeringConnection {
	if in == nil {
		return nil
	}
	out := new(RemotePeeringConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityList) DeepCopyInto(out *SecurityList) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.EgressRules != nil {
		in, out := &in.EgressRules, &out.EgressRules
		*out = make([]EgressSecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IngressRules != nil {
		in, out := &in.IngressRules, &out.IngressRules
		*out = make([]IngressSecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityList.
func (in *SecurityList) DeepCopy() *SecurityList {
	if in == nil {
		return nil
	}
	out := new(SecurityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShapeConfig) DeepCopyInto(out *ShapeConfig) {
	*out = *in
	if in.Nvmes != nil {
		in, out := &in.Nvmes, &out.Nvmes
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShapeConfig.
func (in *ShapeConfig) DeepCopy() *ShapeConfig {
	if in == nil {
		return nil
	}
	out := new(ShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnet) DeepCopyInto(out *Subnet) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.SecurityList != nil {
		in, out := &in.SecurityList, &out.SecurityList
		*out = new(SecurityList)
		(*in).DeepCopyInto(*out)
	}
	if in.DnsLabel != nil {
		in, out := &in.DnsLabel, &out.DnsLabel
		*out = new(string)
		**out = **in
	}
	if in.Ipv6CidrBlockHextet != nil {
		in, out := &in.Ipv6CidrBlockHextet, &out.Ipv6CidrBlockHextet
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnet.
func (in *Subnet) DeepCopy() *Subnet {
	if in == nil {
		return nil
	}
	out := new(Subnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcpOptions) DeepCopyInto(out *TcpOptions) {
	*out = *in
	if in.DestinationPortRange != nil {
		in, out := &in.DestinationPortRange, &out.DestinationPortRange
		*out = new(PortRange)
		(*in).DeepCopyInto(*out)
	}
	if in.SourcePortRange != nil {
		in, out := &in.SourcePortRange, &out.SourcePortRange
		*out = new(PortRange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcpOptions.
func (in *TcpOptions) DeepCopy() *TcpOptions {
	if in == nil {
		return nil
	}
	out := new(TcpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminatePreemptionAction) DeepCopyInto(out *TerminatePreemptionAction) {
	*out = *in
	if in.PreserveBootVolume != nil {
		in, out := &in.PreserveBootVolume, &out.PreserveBootVolume
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminatePreemptionAction.
func (in *TerminatePreemptionAction) DeepCopy() *TerminatePreemptionAction {
	if in == nil {
		return nil
	}
	out := new(TerminatePreemptionAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdpOptions) DeepCopyInto(out *UdpOptions) {
	*out = *in
	if in.DestinationPortRange != nil {
		in, out := &in.DestinationPortRange, &out.DestinationPortRange
		*out = new(PortRange)
		(*in).DeepCopyInto(*out)
	}
	if in.SourcePortRange != nil {
		in, out := &in.SourcePortRange, &out.SourcePortRange
		*out = new(PortRange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdpOptions.
func (in *UdpOptions) DeepCopy() *UdpOptions {
	if in == nil {
		return nil
	}
	out := new(UdpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCN) DeepCopyInto(out *VCN) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.CIDRS != nil {
		in, out := &in.CIDRS, &out.CIDRS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NatGatewayId != nil {
		in, out := &in.NatGatewayId, &out.NatGatewayId
		*out = new(string)
		**out = **in
	}
	if in.InternetGatewayId != nil {
		in, out := &in.InternetGatewayId, &out.InternetGatewayId
		*out = new(string)
		**out = **in
	}
	if in.ServiceGatewayId != nil {
		in, out := &in.ServiceGatewayId, &out.ServiceGatewayId
		*out = new(string)
		**out = **in
	}
	if in.PrivateRouteTableId != nil {
		in, out := &in.PrivateRouteTableId, &out.PrivateRouteTableId
		*out = new(string)
		**out = **in
	}
	if in.PublicRouteTableId != nil {
		in, out := &in.PublicRouteTableId, &out.PublicRouteTableId
		*out = new(string)
		**out = **in
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*Subnet, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Subnet)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NetworkSecurityGroups != nil {
		in, out := &in.NetworkSecurityGroups, &out.NetworkSecurityGroups
		*out = make([]*NSG, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NSG)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DnsLabel != nil {
		in, out := &in.DnsLabel, &out.DnsLabel
		*out = new(string)
		**out = **in
	}
	if in.IsOracleGuaAllocationEnabled != nil {
		in, out := &in.IsOracleGuaAllocationEnabled, &out.IsOracleGuaAllocationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsIpv6Enabled != nil {
		in, out := &in.IsIpv6Enabled, &out.IsIpv6Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCN.
func (in *VCN) DeepCopy() *VCN {
	if in == nil {
		return nil
	}
	out := new(VCN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCNPeering) DeepCopyInto(out *VCNPeering) {
	*out = *in
	if in.DRG != nil {
		in, out := &in.DRG, &out.DRG
		*out = new(DRG)
		(*in).DeepCopyInto(*out)
	}
	if in.PeerRouteRules != nil {
		in, out := &in.PeerRouteRules, &out.PeerRouteRules
		*out = make([]PeerRouteRule, len(*in))
		copy(*out, *in)
	}
	if in.RemotePeeringConnections != nil {
		in, out := &in.RemotePeeringConnections, &out.RemotePeeringConnections
		*out = make([]RemotePeeringConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCNPeering.
func (in *VCNPeering) DeepCopy() *VCNPeering {
	if in == nil {
		return nil
	}
	out := new(VCNPeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VnicAttachment) DeepCopyInto(out *VnicAttachment) {
	*out = *in
	if in.VnicAttachmentId != nil {
		in, out := &in.VnicAttachmentId, &out.VnicAttachmentId
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.NicIndex != nil {
		in, out := &in.NicIndex, &out.NicIndex
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnicAttachment.
func (in *VnicAttachment) DeepCopy() *VnicAttachment {
	if in == nil {
		return nil
	}
	out := new(VnicAttachment)
	in.DeepCopyInto(out)
	return out
}
