apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:="192.168.0.0/16"}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:="10.128.0.0/12"}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OCICluster
    name: "${CLUSTER_NAME}"
    namespace: "${NAMESPACE}"
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: "${CLUSTER_NAME}-control-plane"
    namespace: "${NAMESPACE}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OCICluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  name: "${CLUSTER_NAME}"
spec:
  compartmentId: "${OCI_COMPARTMENT_ID}"
  networkSpec:
    vcn:
      networkSecurityGroups:
        - egressRules:
            - egressRule:
                description: Control Plane Nodes access to Internet
                destination: 0.0.0.0/0
                destinationType: CIDR_BLOCK
                isStateless: false
                protocol: all
          ingressRules:
            - ingressRule:
                description: Kubernetes API endpoint to Kubernetes control plane node(apiserver
                  port) communication
                isStateless: false
                protocol: "6"
                source: 10.0.0.8/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 6443
                    min: 6443
            - ingressRule:
                description: Control plane node to control plane node(apiserver port)
                  communication
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 6443
                    min: 6443
            - ingressRule:
                description: Worker Node to Kubernetes control plane node(apiserver port)
                  communication
                isStateless: false
                protocol: "6"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 6443
                    min: 6443
            - ingressRule:
                description: etcd client communication
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 2379
                    min: 2379
            - ingressRule:
                description: etcd peer
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 2380
                    min: 2380
            - ingressRule:
                description: Antrea Service
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 10349
                    min: 10349
            - ingressRule:
                description: Antrea Service
                isStateless: false
                protocol: "6"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 10349
                    min: 10349
            - ingressRule:
                description: Geneve Service
                isStateless: false
                protocol: "17"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                udpOptions:
                  destinationPortRange:
                    max: 6081
                    min: 6081
            - ingressRule:
                description: Geneve Service
                isStateless: false
                protocol: "17"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                udpOptions:
                  destinationPortRange:
                    max: 6081
                    min: 6081
            - ingressRule:
                description: Path discovery
                icmpOptions:
                  code: 3
                  type: 3
                isStateless: false
                protocol: "1"
                source: 10.0.0.0/16
                sourceType: CIDR_BLOCK
            - ingressRule:
                description: Inbound SSH traffic to control plane nodes
                isStateless: false
                protocol: "6"
                source: 0.0.0.0/0
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 22
                    min: 22
            - ingressRule:
                description: Control Plane to Control Plane Kubelet Communication
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 10250
                    min: 10250
          name: control-plane
          role: control-plane
        - egressRules:
            - egressRule:
                description: Worker Nodes access to Internet
                destination: 0.0.0.0/0
                destinationType: CIDR_BLOCK
                isStateless: false
                protocol: all
          ingressRules:
            - ingressRule:
                description: Inbound SSH traffic to worker nodes
                isStateless: false
                protocol: "6"
                source: 0.0.0.0/0
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 22
                    min: 22
            - ingressRule:
                description: Path discovery
                icmpOptions:
                  code: 3
                  type: 3
                isStateless: false
                protocol: "1"
                source: 10.0.0.0/16
                sourceType: CIDR_BLOCK
            - ingressRule:
                description: Control plane nodes to worker node Kubelet Communication
                isStateless: false
                protocol: "6"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 10250
                    min: 10250
            - ingressRule:
                description: Worker nodes to worker node Kubelet Communication
                isStateless: false
                protocol: "6"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 10250
                    min: 10250
            - ingressRule:
                description: Geneve Service
                isStateless: false
                protocol: "17"
                source: 10.0.0.0/29
                sourceType: CIDR_BLOCK
                udpOptions:
                  destinationPortRange:
                    max: 6081
                    min: 6081
            - ingressRule:
                description: Geneve Service
                isStateless: false
                protocol: "17"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                udpOptions:
                  destinationPortRange:
                    max: 6081
                    min: 6081
            - ingressRule:
                description: Worker node to default NodePort ingress communication
                isStateless: false
                protocol: "6"
                source: 10.0.64.0/20
                sourceType: CIDR_BLOCK
                tcpOptions:
                  destinationPortRange:
                    max: 32767
                    min: 30000
          name: worker
          role: worker
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
  namespace: "${NAMESPACE}"
spec:
  version: "${KUBERNETES_VERSION}"
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  machineTemplate:
    infrastructureRef:
      kind: OCIMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: "${CLUSTER_NAME}-control-plane"
      namespace: "${NAMESPACE}"
  kubeadmConfigSpec:
    clusterConfiguration:
      kubernetesVersion: ${KUBERNETES_VERSION}
      apiServer:
        certSANs: [localhost, 127.0.0.1]
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: oci://{{ ds["id"] }}
    joinConfiguration:
      discovery: {}
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: oci://{{ ds["id"] }}
---
kind: OCIMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      imageId: "${OCI_IMAGE_ID}"
      compartmentId: "${OCI_COMPARTMENT_ID}"
      shape: "${OCI_CONTROL_PLANE_MACHINE_TYPE=VM.Standard.E4.Flex}"
      shapeConfig:
        ocpus: "${OCI_CONTROL_PLANE_MACHINE_TYPE_OCPUS=1}"
      metadata:
        ssh_authorized_keys: "${OCI_SSH_KEY}"
      isPvEncryptionInTransitEnabled: ${OCI_CONTROL_PLANE_PV_TRANSIT_ENCRYPTION=true}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OCIMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      imageId: "${OCI_IMAGE_ID}"
      compartmentId: "${OCI_COMPARTMENT_ID}"
      shape: "${OCI_NODE_MACHINE_TYPE=VM.Standard.E4.Flex}"
      shapeConfig:
        ocpus: "${OCI_NODE_MACHINE_TYPE_OCPUS=1}"
      metadata:
        ssh_authorized_keys: "${OCI_SSH_KEY}"
      isPvEncryptionInTransitEnabled: ${OCI_NODE_PV_TRANSIT_ENCRYPTION=true}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: oci://{{ ds["id"] }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${NODE_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OCIMachineTemplate