---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: ${CLUSTER_NAME}-0
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  topology:
    class: "cluster-class-example"
    version: "${KUBERNETES_VERSION}"
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    workers:
      machineDeployments:
        - class: "worker"
          name: "md-0"
          replicas: ${WORKER_MACHINE_COUNT}
    variables:
      - name: ssh_authorized_keys
        value: ${OCI_SSH_KEY}
      - name: compartmentId
        value: ${OCI_COMPARTMENT_ID}
      - name: imageId
        value: ${OCI_IMAGE_ID}
      - name: subnets
        value:
        - id: ocid1.subnet.oc1.phx.aaaaaaaa7gyvlsu2vxtpiydb5iu5vg3v3cdb63ayavalabcidbh3sjilm5qq
          role: control-plane-endpoint
        - id: ocid1.subnet.oc1.phx.aaaaaaaayou22cspyzamn227zqh3i4wqkv3lk57gaaa2zvd7ahiq2hrabm7q
          role: worker
        - id: ocid1.subnet.oc1.phx.aaaaaaaab2uqa5425ljx6sqdecmdbxkf2lgcvfevcsbsfrkwh5wwgxd6ccta
          role: control-plane