// Code generated by MockGen. DO NOT EDIT.
// Source: cluster_client.go

// Package mock_scope is a generated GoMock package.
package mock_scope

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	scope "github.com/oracle/cluster-api-provider-oci/cloud/scope"
)

// MockClusterScopeClient is a mock of ClusterScopeClient interface.
type MockClusterScopeClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterScopeClientMockRecorder
}

// MockClusterScopeClientMockRecorder is the mock recorder for MockClusterScopeClient.
type MockClusterScopeClientMockRecorder struct {
	mock *MockClusterScopeClient
}

// NewMockClusterScopeClient creates a new mock instance.
func NewMockClusterScopeClient(ctrl *gomock.Controller) *MockClusterScopeClient {
	mock := &MockClusterScopeClient{ctrl: ctrl}
	mock.recorder = &MockClusterScopeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterScopeClient) EXPECT() *MockClusterScopeClientMockRecorder {
	return m.recorder
}

// DeleteApiServerLB mocks base method.
func (m *MockClusterScopeClient) DeleteApiServerLB(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiServerLB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiServerLB indicates an expected call of DeleteApiServerLB.
func (mr *MockClusterScopeClientMockRecorder) DeleteApiServerLB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiServerLB", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteApiServerLB), arg0)
}

// DeleteApiServerNLB mocks base method.
func (m *MockClusterScopeClient) DeleteApiServerNLB(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiServerNLB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiServerNLB indicates an expected call of DeleteApiServerNLB.
func (mr *MockClusterScopeClientMockRecorder) DeleteApiServerNLB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiServerNLB", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteApiServerNLB), arg0)
}

// DeleteDRG mocks base method.
func (m *MockClusterScopeClient) DeleteDRG(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDRG", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDRG indicates an expected call of DeleteDRG.
func (mr *MockClusterScopeClientMockRecorder) DeleteDRG(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDRG", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteDRG), arg0)
}

// DeleteDRGRPCAttachment mocks base method.
func (m *MockClusterScopeClient) DeleteDRGRPCAttachment(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDRGRPCAttachment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDRGRPCAttachment indicates an expected call of DeleteDRGRPCAttachment.
func (mr *MockClusterScopeClientMockRecorder) DeleteDRGRPCAttachment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDRGRPCAttachment", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteDRGRPCAttachment), arg0)
}

// DeleteDRGVCNAttachment mocks base method.
func (m *MockClusterScopeClient) DeleteDRGVCNAttachment(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDRGVCNAttachment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDRGVCNAttachment indicates an expected call of DeleteDRGVCNAttachment.
func (mr *MockClusterScopeClientMockRecorder) DeleteDRGVCNAttachment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDRGVCNAttachment", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteDRGVCNAttachment), arg0)
}

// DeleteInternetGateway mocks base method.
func (m *MockClusterScopeClient) DeleteInternetGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInternetGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInternetGateway indicates an expected call of DeleteInternetGateway.
func (mr *MockClusterScopeClientMockRecorder) DeleteInternetGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInternetGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteInternetGateway), arg0)
}

// DeleteNSGs mocks base method.
func (m *MockClusterScopeClient) DeleteNSGs(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNSGs", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNSGs indicates an expected call of DeleteNSGs.
func (mr *MockClusterScopeClientMockRecorder) DeleteNSGs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNSGs", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteNSGs), arg0)
}

// DeleteNatGateway mocks base method.
func (m *MockClusterScopeClient) DeleteNatGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNatGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNatGateway indicates an expected call of DeleteNatGateway.
func (mr *MockClusterScopeClientMockRecorder) DeleteNatGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNatGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteNatGateway), arg0)
}

// DeleteRouteTables mocks base method.
func (m *MockClusterScopeClient) DeleteRouteTables(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRouteTables", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRouteTables indicates an expected call of DeleteRouteTables.
func (mr *MockClusterScopeClientMockRecorder) DeleteRouteTables(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRouteTables", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteRouteTables), arg0)
}

// DeleteSecurityLists mocks base method.
func (m *MockClusterScopeClient) DeleteSecurityLists(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityLists", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityLists indicates an expected call of DeleteSecurityLists.
func (mr *MockClusterScopeClientMockRecorder) DeleteSecurityLists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityLists", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteSecurityLists), arg0)
}

// DeleteServiceGateway mocks base method.
func (m *MockClusterScopeClient) DeleteServiceGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceGateway indicates an expected call of DeleteServiceGateway.
func (mr *MockClusterScopeClientMockRecorder) DeleteServiceGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteServiceGateway), arg0)
}

// DeleteSubnets mocks base method.
func (m *MockClusterScopeClient) DeleteSubnets(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnets", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnets indicates an expected call of DeleteSubnets.
func (mr *MockClusterScopeClientMockRecorder) DeleteSubnets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnets", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteSubnets), arg0)
}

// DeleteVCN mocks base method.
func (m *MockClusterScopeClient) DeleteVCN(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVCN", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVCN indicates an expected call of DeleteVCN.
func (mr *MockClusterScopeClientMockRecorder) DeleteVCN(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVCN", reflect.TypeOf((*MockClusterScopeClient)(nil).DeleteVCN), arg0)
}

// GetOCIClusterAccessor mocks base method.
func (m *MockClusterScopeClient) GetOCIClusterAccessor() scope.OCIClusterAccessor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOCIClusterAccessor")
	ret0, _ := ret[0].(scope.OCIClusterAccessor)
	return ret0
}

// GetOCIClusterAccessor indicates an expected call of GetOCIClusterAccessor.
func (mr *MockClusterScopeClientMockRecorder) GetOCIClusterAccessor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOCIClusterAccessor", reflect.TypeOf((*MockClusterScopeClient)(nil).GetOCIClusterAccessor))
}

// ReconcileApiServerLB mocks base method.
func (m *MockClusterScopeClient) ReconcileApiServerLB(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileApiServerLB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileApiServerLB indicates an expected call of ReconcileApiServerLB.
func (mr *MockClusterScopeClientMockRecorder) ReconcileApiServerLB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileApiServerLB", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileApiServerLB), arg0)
}

// ReconcileApiServerNLB mocks base method.
func (m *MockClusterScopeClient) ReconcileApiServerNLB(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileApiServerNLB", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileApiServerNLB indicates an expected call of ReconcileApiServerNLB.
func (mr *MockClusterScopeClientMockRecorder) ReconcileApiServerNLB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileApiServerNLB", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileApiServerNLB), arg0)
}

// ReconcileDRG mocks base method.
func (m *MockClusterScopeClient) ReconcileDRG(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileDRG", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileDRG indicates an expected call of ReconcileDRG.
func (mr *MockClusterScopeClientMockRecorder) ReconcileDRG(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileDRG", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileDRG), arg0)
}

// ReconcileDRGRPCAttachment mocks base method.
func (m *MockClusterScopeClient) ReconcileDRGRPCAttachment(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileDRGRPCAttachment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileDRGRPCAttachment indicates an expected call of ReconcileDRGRPCAttachment.
func (mr *MockClusterScopeClientMockRecorder) ReconcileDRGRPCAttachment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileDRGRPCAttachment", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileDRGRPCAttachment), arg0)
}

// ReconcileDRGVCNAttachment mocks base method.
func (m *MockClusterScopeClient) ReconcileDRGVCNAttachment(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileDRGVCNAttachment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileDRGVCNAttachment indicates an expected call of ReconcileDRGVCNAttachment.
func (mr *MockClusterScopeClientMockRecorder) ReconcileDRGVCNAttachment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileDRGVCNAttachment", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileDRGVCNAttachment), arg0)
}

// ReconcileFailureDomains mocks base method.
func (m *MockClusterScopeClient) ReconcileFailureDomains(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileFailureDomains", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileFailureDomains indicates an expected call of ReconcileFailureDomains.
func (mr *MockClusterScopeClientMockRecorder) ReconcileFailureDomains(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileFailureDomains", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileFailureDomains), arg0)
}

// ReconcileInternetGateway mocks base method.
func (m *MockClusterScopeClient) ReconcileInternetGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileInternetGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileInternetGateway indicates an expected call of ReconcileInternetGateway.
func (mr *MockClusterScopeClientMockRecorder) ReconcileInternetGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileInternetGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileInternetGateway), arg0)
}

// ReconcileNSG mocks base method.
func (m *MockClusterScopeClient) ReconcileNSG(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileNSG", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileNSG indicates an expected call of ReconcileNSG.
func (mr *MockClusterScopeClientMockRecorder) ReconcileNSG(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileNSG", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileNSG), arg0)
}

// ReconcileNatGateway mocks base method.
func (m *MockClusterScopeClient) ReconcileNatGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileNatGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileNatGateway indicates an expected call of ReconcileNatGateway.
func (mr *MockClusterScopeClientMockRecorder) ReconcileNatGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileNatGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileNatGateway), arg0)
}

// ReconcileRouteTable mocks base method.
func (m *MockClusterScopeClient) ReconcileRouteTable(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileRouteTable", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileRouteTable indicates an expected call of ReconcileRouteTable.
func (mr *MockClusterScopeClientMockRecorder) ReconcileRouteTable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileRouteTable", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileRouteTable), arg0)
}

// ReconcileServiceGateway mocks base method.
func (m *MockClusterScopeClient) ReconcileServiceGateway(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileServiceGateway", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileServiceGateway indicates an expected call of ReconcileServiceGateway.
func (mr *MockClusterScopeClientMockRecorder) ReconcileServiceGateway(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileServiceGateway", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileServiceGateway), arg0)
}

// ReconcileSubnet mocks base method.
func (m *MockClusterScopeClient) ReconcileSubnet(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileSubnet", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileSubnet indicates an expected call of ReconcileSubnet.
func (mr *MockClusterScopeClientMockRecorder) ReconcileSubnet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileSubnet", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileSubnet), arg0)
}

// ReconcileVCN mocks base method.
func (m *MockClusterScopeClient) ReconcileVCN(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileVCN", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileVCN indicates an expected call of ReconcileVCN.
func (mr *MockClusterScopeClientMockRecorder) ReconcileVCN(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileVCN", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileVCN), arg0)
}

// ReconcileBlockVolume mocks base method.
func (m *MockClusterScopeClient) ReconcileBlockVolume(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileBlockVolume", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileBlockVolume indicates an expected call of ReconcileBlockVolume.
func (mr *MockClusterScopeClientMockRecorder) ReconcileBlockVolume(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileBlockVolume", reflect.TypeOf((*MockClusterScopeClient)(nil).ReconcileBlockVolume), arg0)
}

// SetRegionKey mocks base method.
func (m *MockClusterScopeClient) SetRegionKey(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRegionKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRegionKey indicates an expected call of SetRegionKey.
func (mr *MockClusterScopeClientMockRecorder) SetRegionKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegionKey", reflect.TypeOf((*MockClusterScopeClient)(nil).SetRegionKey), arg0)
}

// SetRegionCode indicates an expected call of SetRegionCode.
func (mr *MockClusterScopeClientMockRecorder) SetRegionCode(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegionKey", reflect.TypeOf((*MockClusterScopeClient)(nil).SetRegionKey), ctx)
}
