[book]
authors = ["The Cluster API Provider for OCI Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "Kubernetes Cluster API Provider for Oracle Cloud Infrastructure"

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
curly-quotes = false
git-repository-url = "https://github.com/oracle/cluster-api-provider-oci"
additional-css = ["./src/css/mdbook-admonish.css"]
# no-section-label = true
