name: Publish Cluster API Provider Book
on:
  # Rebuild docs when a release is published
  release:
    types: [published]
  # Enable manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir -p mdbook
        archive_path="${RUNNER_TEMP}/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz"
        curl -sSL -o "${archive_path}" https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf "${archive_path}" --directory=./mdbook
        echo "${PWD}/mdbook" >> "${GITHUB_PATH}"
        cargo install --version 1.8.0 mdbook-admonish
    - name: Deploy Book to GitHub Pages
      run: |
        # Build the HTML content
        mdbook build -d book/ docs/

        # Create and switch to the gh-pages work tree
        git worktree add gh-pages gh-pages
        cd $GITHUB_WORKSPACE/gh-pages

        git config user.name "GitHub Actions"
        git config user.email "oci-dax-tools_ww@oracle.com"

        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *

        mv $GITHUB_WORKSPACE/docs/book/* $GITHUB_WORKSPACE/gh-pages
        touch $GITHUB_WORKSPACE/gh-pages/.nojekyll

        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force-with-lease
