name: Macaron check-github-actions

on:
  push:
    branches:
      - main
      - master
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  schedule:
    - cron: "20 15 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macaron-check-github-actions:
    runs-on: ubuntu-latest
    name: Macaron policy verification
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Run Macaron check-github-actions policy
        uses: oracle/macaron@b31acfe389133a5587d9639063ec70cb84e7bc47 # v0.23.0
        with:
          repo_path: ./
          policy_file: check-github-actions
          policy_purl: pkg:github.com/oracle/cluster-api-provider-oci@.*
